blank_lines_upper_bound = 2
brace_style = "SameLineWhere"
chain_width = 120
comment_width = 120
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
fn_call_width = 100
fn_params_layout = "Compressed"
format_code_in_doc_comments = true
hard_tabs = false
imports_layout = "Horizontal"
max_width = 120
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
tab_spaces = 4
trailing_comma = "Vertical"
